-- MySQL Script generated by MySQL Workbench
-- Sun Oct  8 15:07:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bionbe-dev
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bionbe-dev` ;

-- -----------------------------------------------------
-- Schema bionbe-dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bionbe-dev` DEFAULT CHARACTER SET utf8 ;
USE `bionbe-dev` ;

-- -----------------------------------------------------
-- Table `bionbe-dev`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bionbe-dev`.`users` ;

CREATE TABLE IF NOT EXISTS `bionbe-dev`.`users` (
  `id` VARCHAR(40) NOT NULL,
  `company_name` VARCHAR(255) NOT NULL,
  `company_email` VARCHAR(100) NOT NULL,
  `manager_lastname` VARCHAR(150) NOT NULL,
  `manager_firstname` VARCHAR(20) NOT NULL,
  `manager_email` VARCHAR(100) NOT NULL,
  `manager_phone` VARCHAR(20) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updateAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `manager_phone_UNIQUE` (`manager_phone` ASC) VISIBLE,
  UNIQUE INDEX `manager_email_UNIQUE` (`manager_email` ASC) VISIBLE,
  UNIQUE INDEX `company_name_UNIQUE` (`company_name` ASC) VISIBLE,
  UNIQUE INDEX `company_email_UNIQUE` (`company_email` ASC) VISIBLE)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
